# Generated by Django 5.0.2 on 2024-02-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TordiApp', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='Avatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='Bio',
        ),
    ]
