# Generated by Django 5.0.2 on 2024-02-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TordiApp', '0003_rename_avatar_profile_avatar_rename_bio_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
