# Generated by Django 5.0.2 on 2024-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TordiApp', '0005_profile_pic_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bicoin', models.FloatField(max_length=20)),
                ('Etherium', models.FloatField(max_length=20)),
                ('Usdt', models.FloatField(max_length=20)),
                ('Dogecoin', models.FloatField(max_length=20)),
                ('Bnb', models.FloatField(max_length=20)),
            ],
        ),
    ]
