# Generated by Django 5.0.2 on 2024-03-31 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bronzs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BitPlan1', models.CharField(max_length=250)),
                ('Bitplan2', models.CharField(max_length=250)),
                ('Bitplan3', models.CharField(max_length=250)),
                ('Bitplan4', models.CharField(max_length=250)),
                ('Bitplan5', models.CharField(max_length=250)),
                ('Ethplan1', models.CharField(max_length=250)),
                ('Ethplan2', models.CharField(max_length=250)),
                ('Ethplan3', models.CharField(max_length=250)),
                ('Ethplan4', models.CharField(max_length=250)),
                ('Ethplan5', models.CharField(max_length=250)),
                ('Bnbplan1', models.CharField(max_length=250)),
                ('Bnbplan2', models.CharField(max_length=250)),
                ('Bnbplan3', models.CharField(max_length=250)),
                ('Bnbplan4', models.CharField(max_length=250)),
                ('Bnbplan5', models.CharField(max_length=250)),
                ('Dogeplan1', models.CharField(max_length=250)),
                ('Dogeplan2', models.CharField(max_length=250)),
                ('Dogeplan3', models.CharField(max_length=250)),
                ('Dogeplan4', models.CharField(max_length=250)),
                ('Dogeplan5', models.CharField(max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BitPlan1', models.CharField(max_length=250)),
                ('Bitplan2', models.CharField(max_length=250)),
                ('Bitplan3', models.CharField(max_length=250)),
                ('Bitplan4', models.CharField(max_length=250)),
                ('Bitplan5', models.CharField(max_length=250)),
                ('Ethplan1', models.CharField(max_length=250)),
                ('Ethplan2', models.CharField(max_length=250)),
                ('Ethplan3', models.CharField(max_length=250)),
                ('Ethplan4', models.CharField(max_length=250)),
                ('Ethplan5', models.CharField(max_length=250)),
                ('Bnbplan1', models.CharField(max_length=250)),
                ('Bnbplan2', models.CharField(max_length=250)),
                ('Bnbplan3', models.CharField(max_length=250)),
                ('Bnbplan4', models.CharField(max_length=250)),
                ('Bnbplan5', models.CharField(max_length=250)),
                ('Dogeplan1', models.CharField(max_length=250)),
                ('Dogeplan2', models.CharField(max_length=250)),
                ('Dogeplan3', models.CharField(max_length=250)),
                ('Dogeplan4', models.CharField(max_length=250)),
                ('Dogeplan5', models.CharField(max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Silver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BitPlan1', models.CharField(max_length=250)),
                ('Bitplan2', models.CharField(max_length=250)),
                ('Bitplan3', models.CharField(max_length=250)),
                ('Bitplan4', models.CharField(max_length=250)),
                ('Bitplan5', models.CharField(max_length=250)),
                ('Ethplan1', models.CharField(max_length=250)),
                ('Ethplan2', models.CharField(max_length=250)),
                ('Ethplan3', models.CharField(max_length=250)),
                ('Ethplan4', models.CharField(max_length=250)),
                ('Ethplan5', models.CharField(max_length=250)),
                ('Bnbplan1', models.CharField(max_length=250)),
                ('Bnbplan2', models.CharField(max_length=250)),
                ('Bnbplan3', models.CharField(max_length=250)),
                ('Bnbplan4', models.CharField(max_length=250)),
                ('Bnbplan5', models.CharField(max_length=250)),
                ('Dogeplan1', models.CharField(max_length=250)),
                ('Dogeplan2', models.CharField(max_length=250)),
                ('Dogeplan3', models.CharField(max_length=250)),
                ('Dogeplan4', models.CharField(max_length=250)),
                ('Dogeplan5', models.CharField(max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
